### ISSUE TITLE
Symbol not found: __ZTVN6icu_559ErrorCodeE

### ISSUE THREAD

**Issue by lancedikson** [flowaccount/node-icu-tokenizer#1]
Hi, I suppose, this repo is a fork of that old package with a missing repo, right? https://www.npmjs.com/package/node-icu-tokenizer. 

Did you get a chance to run it successfully? As it fails for me. The original one is not even building during `npm install`. This fork is building at least, but when I run it, it fails with the following error stack trace:

```
/Users/lancedikson/Projects/videoly/testing-icu-tokenizer/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: dlopen(/Users/lancedikson/Projects/videoly/testing-icu-tokenizer/node_modules/@flowaccount/node-icu-tokenizer/build/Release/node-icu-tokenizer.node, 1): Symbol not found: __ZTVN6icu_559ErrorCodeE
  Referenced from: /Users/lancedikson/Projects/videoly/testing-icu-tokenizer/node_modules/@flowaccount/node-icu-tokenizer/build/Release/node-icu-tokenizer.node
  Expected in: flat namespace
 in /Users/lancedikson/Projects/videoly/testing-icu-tokenizer/node_modules/@flowaccount/node-icu-tokenizer/build/Release/node-icu-tokenizer.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:815:18)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at bindings (/Users/lancedikson/Projects/videoly/testing-icu-tokenizer/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/lancedikson/Projects/videoly/testing-icu-tokenizer/node_modules/@flowaccount/node-icu-tokenizer/index.js:1:40)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
```

I'm using MacOS Catalina, with Homebrew and the icu4c 67.1 installed. 
Installation went well as I can understand from the log:
```
npm i @flowaccount/node-icu-tokenizer --save

> @flowaccount/node-icu-tokenizer@1.0.5 install /Users/lancedikson/Projects/videoly/testing-icu-tokenizer/node_modules/@flowaccount/node-icu-tokenizer
> node-gyp rebuild

  CC(target) Release/obj.target/nothing/../../node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
  CXX(target) Release/obj.target/node-icu-tokenizer/node-icu-tokenizer.o
  SOLINK_MODULE(target) Release/node-icu-tokenizer.node
ld: warning: ignoring file /Users/lancedikson/Projects/videoly/testing-icu-tokenizer/node_modules/@flowaccount/node-icu-tokenizer/lib/libicui18n.so.55, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
ld: warning: ignoring file /Users/lancedikson/Projects/videoly/testing-icu-tokenizer/node_modules/@flowaccount/node-icu-tokenizer/lib/libicudata.so.55, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
ld: warning: ignoring file /Users/lancedikson/Projects/videoly/testing-icu-tokenizer/node_modules/@flowaccount/node-icu-tokenizer/lib/libicuio.so.55, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
ld: warning: ignoring file /Users/lancedikson/Projects/videoly/testing-icu-tokenizer/node_modules/@flowaccount/node-icu-tokenizer/lib/libiculx.so.55, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
ld: warning: ld: warning: ignoring file /Users/lancedikson/Projects/videoly/testing-icu-tokenizer/node_modules/@flowaccount/node-icu-tokenizer/lib/libicule.so.55, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
ld: warning: ignoring file /Users/lancedikson/Projects/videoly/testing-icu-tokenizer/node_modules/@flowaccount/node-icu-tokenizer/lib/libicutu.so.55, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
ignoring file /Users/lancedikson/Projects/videoly/testing-icu-tokenizer/node_modules/@flowaccount/node-icu-tokenizer/lib/libicuuc.so.55, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
+ @flowaccount/node-icu-tokenizer@1.0.5
updated 1 package and audited 57 packages in 10.266s
```

**Comment by wickstargazer** [comment]
Hi yes! Thank you for messaging we thought we are the only creatures left who is using this package. 

It builds and runs on `unix` fine, but on `windows` i cannot figure out after the build whats breaking. 

That was a goal i wanted to accomplish but lack the right know-how. 

From the changes, this lib is a stand-alone and **no need for any pre-requisite install** on your machine/server. It is using the **static make files for icu library**

Maybe thats one of the issue for the windows build. The **static lib** might be wrong. Or the `dll binding` is not ok. Maybe i got the `binding.gyp` wrong

**Comment by lancedikson** [comment]
Thanks for your answer! But for some reason it doesn't work for me on both — MacOS and Linux Ubuntu (heroku-18).
The exception in both cases the same: 
```
2020-08-04T12:32:36.023318+00:00 app[web.1]: > testing-icu-tokenizer@0.0.0 start /app
2020-08-04T12:32:36.023319+00:00 app[web.1]: > node ./bin/www
2020-08-04T12:32:36.023319+00:00 app[web.1]: 
2020-08-04T12:32:36.179635+00:00 app[web.1]: /app/node_modules/bindings/bindings.js:121
2020-08-04T12:32:36.179636+00:00 app[web.1]:         throw e;
2020-08-04T12:32:36.179637+00:00 app[web.1]:         ^
2020-08-04T12:32:36.179637+00:00 app[web.1]: 
2020-08-04T12:32:36.179638+00:00 app[web.1]: Error: libicuuc.so.55: cannot open shared object file: No such file or directory
2020-08-04T12:32:36.179638+00:00 app[web.1]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1187:18)
2020-08-04T12:32:36.179639+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:985:32)
2020-08-04T12:32:36.179639+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
2020-08-04T12:32:36.179639+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:1025:19)
2020-08-04T12:32:36.179640+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:72:18)
2020-08-04T12:32:36.179640+00:00 app[web.1]:     at bindings (/app/node_modules/bindings/bindings.js:112:48)
2020-08-04T12:32:36.179641+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/@flowaccount/node-icu-tokenizer/index.js:1:40)
2020-08-04T12:32:36.179641+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:1137:30)
2020-08-04T12:32:36.179641+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
2020-08-04T12:32:36.179642+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:985:32)
2020-08-04T12:32:36.187940+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-08-04T12:32:36.188205+00:00 app[web.1]: npm ERR! errno 1
2020-08-04T12:32:36.191543+00:00 app[web.1]: npm ERR! testing-icu-tokenizer@0.0.0 start: `node ./bin/www`
2020-08-04T12:32:36.191631+00:00 app[web.1]: npm ERR! Exit status 1
2020-08-04T12:32:36.191743+00:00 app[web.1]: npm ERR! 
2020-08-04T12:32:36.191817+00:00 app[web.1]: npm ERR! Failed at the testing-icu-tokenizer@0.0.0 start script.
2020-08-04T12:32:36.191886+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-08-04T12:32:36.196655+00:00 app[web.1]: 
2020-08-04T12:32:36.196841+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-08-04T12:32:36.196958+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-08-04T12_32_36_193Z-debug.log
2020-08-04T12:32:40.844937+00:00 heroku[web.1]: Starting process with command `npm start`
2020-08-04T12:32:43.512647+00:00 heroku[web.1]: Process exited with status 1
2020-08-04T12:32:43.555871+00:00 heroku[web.1]: State changed from starting to crashed
```

Are you running it on a Linux server without issues? Interesting, what's the problem with my build then? 🤔  There must be something with the way node-gyp rebuilds the sources.

**Comment by lancedikson** [comment]
Oh, the exception is not the same, it's just the stack trace is very similar, but that's weird that there's a missing file on server — I have it locally and would expect it to be there as well.

**Comment by lancedikson** [comment]
Do you have an idea what could be wrong with it? Or where I should start from as I've never debugged a package with some CPP modules compiling and binding to node? :)

**Comment by wickstargazer** [comment]
Hi @lancedikson! We just figured it out... It is working on linux smoothly now, with the latest version.

Sorry for the delay, we figured out that the version 55 was not working with the new node version. So we upgrade it to version 60.2 and its working without having to install anything locally 😄 
Everything is statically built into the lib.. Just the size of the node_module will be a bit more than usual

Will be working on the windows build in a big while to come

**Comment by lancedikson** [comment]
Great news! Thanks for the update, @wickstargazer!
I tried it on Heroku and it works, which is amazing! However, there are problems with installing it on Mac:
```
(base) ➜  testing-icu-tokenizer git:(master) npm i

> @flowaccount/node-icu-tokenizer@1.0.10 install /Users/lancedikson/Projects/videoly/testing-icu-tokenizer/node_modules/@flowaccount/node-icu-tokenizer
> node-gyp rebuild

  CC(target) Release/obj.target/nothing/../../node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 30, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 45, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 248, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/nothing.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/lancedikson/.nvm/versions/node/v12.3.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/lancedikson/.nvm/versions/node/v12.3.1/bin/node" "/Users/lancedikson/.nvm/versions/node/v12.3.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/lancedikson/Projects/videoly/testing-icu-tokenizer/node_modules/@flowaccount/node-icu-tokenizer
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @flowaccount/node-icu-tokenizer@1.0.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @flowaccount/node-icu-tokenizer@1.0.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lancedikson/.npm/_logs/2020-08-13T16_59_41_046Z-debug.log
```

**Comment by wickstargazer** [comment]
i will fix the binding.gyp tomorrow for that part, i think we fixed for linux and dint care about mac or windows 🗡️
